package accesodatos.modelos;
// Generated 03-feb-2023 17:33:46 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private Integer codigo;
     private String titulo;
     private String autor;

    public Libros() {
    }

	
    public Libros(String titulo) {
        this.titulo = titulo;
    }
    public Libros(String titulo, String autor) {
       this.titulo = titulo;
       this.autor = autor;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + Objects.hashCode(this.codigo);
        hash = 83 * hash + Objects.hashCode(this.titulo);
        hash = 83 * hash + Objects.hashCode(this.autor);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Libros other = (Libros) obj;
        if (!Objects.equals(this.titulo, other.titulo)) {
            return false;
        }
        if (!Objects.equals(this.autor, other.autor)) {
            return false;
        }
        if (!Objects.equals(this.codigo, other.codigo)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Libros{" + "codigo=" + codigo + ", titulo=" + titulo + ", autor=" + autor + '}';
    }




}


