package accesodatos.modelos;
// Generated 03-feb-2023 17:33:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;

/**
 * Prestamos generated by hbm2java
 */
public class Prestamos  implements java.io.Serializable {


     private PrestamosId id;
     private String documento;
     private Date fechadevolucion;

    public Prestamos() {
    }

	
    public Prestamos(PrestamosId id, String documento) {
        this.id = id;
        this.documento = documento;
    }
    public Prestamos(PrestamosId id, String documento, Date fechadevolucion) {
       this.id = id;
       this.documento = documento;
       this.fechadevolucion = fechadevolucion;
    }
   
    public PrestamosId getId() {
        return this.id;
    }
    
    public void setId(PrestamosId id) {
        this.id = id;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public Date getFechadevolucion() {
        return this.fechadevolucion;
    }
    
    public void setFechadevolucion(Date fechadevolucion) {
        this.fechadevolucion = fechadevolucion;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.id);
        hash = 89 * hash + Objects.hashCode(this.documento);
        hash = 89 * hash + Objects.hashCode(this.fechadevolucion);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Prestamos other = (Prestamos) obj;
        if (!Objects.equals(this.documento, other.documento)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.fechadevolucion, other.fechadevolucion)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Prestamos{" + "id=" + id + ", documento=" + documento + ", fechadevolucion=" + fechadevolucion + '}';
    }




}


