package accesodatos.modelos;
// Generated 03-feb-2023 17:33:46 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Socios generated by hbm2java
 */
public class Socios  implements java.io.Serializable {


     private String documento;
     private String nombre;
     private String domicilio;

    public Socios() {
    }

	
    public Socios(String documento) {
        this.documento = documento;
    }
    public Socios(String documento, String nombre, String domicilio) {
       this.documento = documento;
       this.nombre = nombre;
       this.domicilio = domicilio;
    }
   
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + Objects.hashCode(this.documento);
        hash = 37 * hash + Objects.hashCode(this.nombre);
        hash = 37 * hash + Objects.hashCode(this.domicilio);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Socios other = (Socios) obj;
        if (!Objects.equals(this.documento, other.documento)) {
            return false;
        }
        if (!Objects.equals(this.nombre, other.nombre)) {
            return false;
        }
        if (!Objects.equals(this.domicilio, other.domicilio)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Socios{" + "documento=" + documento + ", nombre=" + nombre + ", domicilio=" + domicilio + '}';
    }




}


